import { RuntimeError } from "../model/errors";
import type { ContextSnapshot, ModelContext, PredictionResult } from "../model/types";
import type { InputSnapshot } from "../data/input-snapshots";

export interface CaseDescriptor { readonly caseId: string; readonly inputSnapshotId: string; readonly trainingSnapshotId?: string; readonly sql?: string; readonly typedParams?: readonly unknown[]; readonly targetName?: string; readonly modelId: "tabicl-v2"; readonly artifactDigest: string; readonly contextKey: string; readonly context?: ModelContext | ContextSnapshot; readonly scenarioIds: readonly string[]; readonly resultRequestIds: readonly string[]; readonly trainingMutable: false; }
export interface CommonViewDescriptor { readonly sourceCaseId: string; readonly inputSnapshotId: string; readonly modelId: CaseDescriptor["modelId"]; readonly artifactDigest: string; readonly contextKey: string; readonly resultRequestIds: readonly string[]; readonly trainingMutable: false; }
export function createCaseDescriptor(input: Omit<CaseDescriptor, "trainingMutable" | "scenarioIds" | "resultRequestIds"> & { scenarioIds?: readonly string[]; resultRequestIds?: readonly string[] }): CaseDescriptor { return { ...input, trainingMutable: false, scenarioIds: [...(input.scenarioIds ?? [])], resultRequestIds: [...(input.resultRequestIds ?? [])] }; }
export function openInCommon(caseDescriptor: CaseDescriptor): CommonViewDescriptor { return { sourceCaseId: caseDescriptor.caseId, inputSnapshotId: caseDescriptor.inputSnapshotId, modelId: caseDescriptor.modelId, artifactDigest: caseDescriptor.artifactDigest, contextKey: caseDescriptor.contextKey, resultRequestIds: [...caseDescriptor.resultRequestIds], trainingMutable: false }; }
export function assertCaseTrainingImmutable(caseDescriptor: CaseDescriptor): never { throw new RuntimeError("UNSUPPORTED_CAPABILITY", `Case ${caseDescriptor.caseId} has a fixed training context`); }
export function retainCaseResult(caseDescriptor: CaseDescriptor, result: PredictionResult): CaseDescriptor { if (result.contextKey !== caseDescriptor.contextKey) throw new RuntimeError("CONTEXT_INCOMPATIBLE", "Result context does not match Case"); return { ...caseDescriptor, resultRequestIds: [...caseDescriptor.resultRequestIds, result.requestId] }; }
